name: dev release
on:
  push:
    branches:
      - develop
jobs:
  build:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Bump prerelease version of root package
        run: npm version --no-git-tag-version prerelease
      - name: Get current package version
        id: package_version
        run: echo "::set-output name=package_version::$(node -pe "require('./package.json').version")"        
      - name: Export package version
        env:
          PACKAGE_VERSION: ${{ steps.package_version.outputs.package_version }}
      - name: Build package
        run: yarn run build
      - name: Publish to NPM
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN : ${{ secrets.NPM_TOKEN }}
      - name: Commit files
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "[CI Skip] ci: publish prerelease" -n
          git push          
