name: release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NPM_CONFIG_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
